### ISSUE TITLE
Homepage URL on GitHub project page results in a 404 error

### ISSUE THREAD

**Issue by cvrebert** [andreazevedo/dispatch-github#8]
On https://github.com/andreazevedo/dispatch-github , there is a link to http://dispatch.databinder.net/Project+Setup.html , but this link currently results in an HTTP 404 error page.

**Comment by eranmeir** [comment]
Yeah, this should probably be changed to just http://dispatch.databinder.net/

**Comment by andreazevedo** [comment]
Thank you!
